# Evaluation de Theories des jeux

In [1]:
from sources import GameMatrix
import numpy as np

In [2]:
game_matrix = GameMatrix()
matrix_df = game_matrix.generate_df()
matrix_df

W    S    G    E    M    T    N
W   D6  D10   D6  D12  D10   D3   D4
S   D6   D6   D3   D6   D6  D12   D4
G   D6  D12   D6   D4   D6  D10   D3
E   D3   D4   D6   D6  D12   D4   D6
M  D10   D6  D12   D3   D6   D6   D4
T   D6   D4  D10  D10   D6   D3  D12
N  D12  D10  D10   D3   D4   D6   D6

Calculons maintenant les probabilites de gain en fonction des differents duels: <br>
**Exemple**:
- Le joueur `1` fait `E`
- Le joueur `2` fait `W`    
- Le joueur `1` joue `D3`
- Le joueur `2` joue `D12`
- La probabilite que le joueur `1` gagne est donc la probabilite que le lancer d'un de de trois faces soit superieur a celui de 12 faces soit : $\frac{3-1}{2*12}=\frac{1}{12}\approx 0.083$

In [3]:
dice_1 = 10
dice_2 = 6
victory_case = np.zeros((dice_1, dice_2))
for i in range(dice_1):
    for j in range(dice_2):
        if i> j:
            victory_case[i, j] = 1
        elif i == j:
            victory_case[i, j] = 0
        else:
            victory_case[i, j] = 2

total_case = dice_1 * dice_2
player_1_win_prob = (victory_case == 1).sum() / total_case
player_2_win_prob = (victory_case == 2).sum() / total_case
draw_prob = (victory_case == 0).sum() / total_case
print(f"Player 1 win rate: {player_1_win_prob:.2f}")
print(f"Player 2 win rate: {player_2_win_prob:.2f}")
print(f"Draw rate: {draw_prob:.2f}")


Player 1 win rate: 0.65
Player 2 win rate: 0.25
Draw rate: 0.10


In [4]:
game_matrix.init_winning_probs()
game_matrix.winnging_probs


array([[0.41666667, 0.45      , 0.41666667, 0.45833333, 0.45      ,
        0.33333333, 0.375     ],
       [0.41666667, 0.41666667, 0.33333333, 0.41666667, 0.41666667,
        0.45833333, 0.375     ],
       [0.41666667, 0.45833333, 0.41666667, 0.375     , 0.41666667,
        0.45      , 0.33333333],
       [0.33333333, 0.375     , 0.41666667, 0.41666667, 0.45833333,
        0.375     , 0.41666667],
       [0.45      , 0.41666667, 0.45833333, 0.33333333, 0.41666667,
        0.41666667, 0.375     ],
       [0.41666667, 0.375     , 0.45      , 0.45      , 0.41666667,
        0.33333333, 0.45833333],
       [0.45833333, 0.45      , 0.45      , 0.33333333, 0.375     ,
        0.41666667, 0.41666667]])

Cherchons la strategie qui a le plus de gain en terme d'esperance.

In [5]:
(game_matrix.dice_matrix.sum(axis=1)+game_matrix.n_strategies)/(game_matrix.n_strategies*2)

array([4.14285714, 3.57142857, 3.85714286, 3.42857143, 3.85714286,
       4.14285714, 4.14285714])

Cherchons la strategie qui a le plus de chance d'avoir au minimum un match nul en moyenne

In [7]:
game_matrix.init_winning_probs(count_draws=True)
game_matrix.winnging_probs.mean(axis=1)

array([0.58571429, 0.5952381 , 0.59047619, 0.60119048, 0.59047619,
       0.58571429, 0.58571429])